FROM python:3.9
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /django-pokerfacowaty-com

ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=1.5.0

RUN pip install "poetry==$POETRY_VERSION"
RUN poetry config virtualenvs.in-project true