services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: pokerfacowaty-com-dev
    command: sh -c "poetry install --no-root && . .venv/bin/activate && python3 manage.py migrate && python3 manage.py collectstatic --no-input --clear && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
    # Don't forget to attach volumes for the db, MC_LOG_DIR, PLAYLIST_CSV_DIR, STATIC_ROOT if needed
      - "../django-pokerfacowaty-com:/django-pokerfacowaty-com"
    environment:
      - ALLOWED_HOSTS=[""]
      - CSRF_TRUSTED_ORIGINS=[""]
      - CSRF_COOKIE_SECURE=True
      - DEBUG=False
      - MC_LOG_DIR=
      - PLAYLIST_CSV_DIR=
      - SECRET_KEY=
      - SESSION_COOKIE_SECURE=True
      - STATIC=
      - STATIC_ROOT=
