# Generated by Django 4.2 on 2023-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=100)),
                ('SHORT_TITLE', models.CharField(max_length=20)),
                ('LAST_UPDATED', models.DateTimeField()),
                ('CSV_FILENAME', models.CharField(max_length=100)),
                ('VISIBILITY', models.CharField(choices=[('PU', 'Public'), ('UN', 'Unlisted'), ('PR', 'Private')], default='PR', max_length=20)),
            ],
        ),
    ]
