# Generated by Django 4.2 on 2023-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='DESCRIPTION',
            field=models.TextField(blank=True),
        ),
    ]
