# Generated by Django 4.1.6 on 2023-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaMLPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=100)),
                ('SHORT_TITLE', models.CharField(max_length=20)),
                ('LAST_EDITED', models.DateTimeField()),
                ('PAML_CONTENT', models.TextField(blank=True)),
                ('VISIBILITY', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PR', max_length=20)),
            ],
        ),
    ]
