# Generated by Django 4.1.6 on 2023-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTIST', models.CharField(blank=True, max_length=50)),
                ('ALBUM', models.CharField(blank=True, max_length=50)),
                ('SONGS', models.CharField(blank=True, max_length=250)),
                ('NOTE', models.TextField(blank=True)),
                ('DOWNLOADED', models.BooleanField(default=False)),
                ('ADDED_TO_LIBRARY', models.BooleanField(default=False)),
            ],
        ),
    ]
