# Generated by Django 4.1.6 on 2023-02-13 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicentry',
            name='MADE',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
